### ISSUE TITLE
Feature Request: Mouse wheel zooming should not require CTRL

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [Aqovia/OctopusPuppet#8]
~~**Support zooming using mouse wheel**~~
~~The panning experience is awesome. One last thing it lacks is zooming :)~~

OK, only just noticed that hovering over the zoom slider gives me a list of gestures, so mousewheel is supported.

Then I think just a minor thing is that since 'just mousewheel' doesn't do anything, it might as well accommodate zooming, so that CTRL is not required.

**Comment by taliesins** [comment]
I think ctrl + mouse wheel is the standard used across all windows apps for zooming in and out. Try it out in your browser.

**Comment by slawomir-brzezinski-at-interxion** [comment]
I'm well aware of th CTRL+wheel convention, but it only started as a shortcut for scaling the UI for readability (fonts etc), not zooming-in.

See how all map websites, or those UIs that deal with inherently zoomable things like SVGs, allow you to zoom without CTRL. And in some of them CTRL+Wheel gets intercepted by the browser and just the fonts get scaled.

If memory serves me well, the mapping websits like google or bing only started handling the CTRL later on. They still allow CTRLless because it's just convenient.
